AvondspelPortal/Models/LoginViewModel.cs
using Avondspel.Domain.DataAnnotation;
using Avondspel.Domain.Enum;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using DefaultValueAttribute = System.ComponentModel.DefaultValueAttribute;

namespace Avondspel.Portal.Models
{
    public class LoginViewModel
    {
        [Required]
        [UIHint("Password")]
        [PasswordPropertyText]
        public string Password { get; set; } = null!;

        [Required(ErrorMessage = "Wat is jou naam?")]
        public string Name { get; set; } = null!;
        [EmailAddress]
        [Required(ErrorMessage = "Wat is jou email?")]
        public string Email { get; set; } = null!;

        [Required(ErrorMessage = "Wat is jou geslacht?")]
        [DefaultValue(Geslacht.LieverNiet)]
        public Geslacht Gender { get; set; }

        [AgeValidation]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Wanneer ben jij geboren?")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Birthday { get; set; }

        [Required(ErrorMessage = "Straat?")]
        public string Street { get; set; } = null!;

        [Required(ErrorMessage = "Stad?")]
        public string City { get; set; } = null!;

        [Required(ErrorMessage = "Huisnummer?")]
        public string HouseNumber { get; set; } = null!;

        //Standaard geen lactose intollerantie
        [DefaultValue(false)]
        public bool Lactose { get; set; }

        //Standaard geen notenallergie
        [DefaultValue(false)]
        public bool Notenallergie { get; set; }

        //Standaard niet vega
        [DefaultValue(false)]
        public bool Vega { get; set; }

        //Standaard geen alcohol willen
        [DefaultValue(false)]
        public bool Alcohol { get; set; }
    }
}

AvondspelPortal/Controllers/BordspelController.cs
using Avondspel.Domain;
using Avondspel.Services.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Avondspel.Portal.Controllers
{
    public class BordspelController : Controller
    {
        private readonly IRepositoryBordspellen repositoryBordspellen;
        private readonly UserManager<IdentityUser> _userManager;

        public BordspelController(IRepositoryBordspellen _repositoryBordspellen, UserManager<IdentityUser> userManager)
        {
            repositoryBordspellen = _repositoryBordspellen;
            _userManager = userManager;
        }

        public Bordspel imageConverter(Bordspel bordspelModel, IFormFile imageFile)
        {
            using (var ms = new MemoryStream())
            {
                imageFile.CopyTo(ms);
                var fileInBytes = ms.ToArray();
                string imageString = Convert.ToBase64String(fileInBytes);
                bordspelModel.foto = imageString;
            }
            return bordspelModel;
        }

        //GET: Bordspel
        public ViewResult Index()
        {
            var bordspellen = repositoryBordspellen.GetBordspellen();
            return View(bordspellen);

        }

        //GET: Bordspel/Details/{?id}
        public ViewResult Details(int id)
        {
            Bordspel? bordspel = repositoryBordspellen.GetBordspelById(id);
            return View(bordspel);
        }

        //GET: Bordspel/Create
        [Authorize(Policy = "Gebruiker")]
        public IActionResult Create()
        {
            return View();
        }

        //POST: Bordspel/Create
        [Authorize(Policy = "Gebruiker")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Bordspel bordspelModel, IFormFile imageFile)
        {
            if (imageFile != null)
            {
                imageConverter(bordspelModel, imageFile);
                Task.Delay(1000);
            }
            var id = _userManager.GetUserId(User);
            bordspelModel.GebruikerId = id;
            ModelState.Remove("imageFile");
            ModelState.Remove("GebruikerId");
            if (ModelState.IsValid)
            {
                repositoryBordspellen.InsertBordspel(bordspelModel);
                repositoryBordspellen.save();
                return RedirectToAction("Index");
            }
            return View(bordspelModel);
        }

        //GET: Bordspel/Edit/{?id}
        [Authorize(Policy = "Gebruiker")]
        public ActionResult Edit(int id)
        {
            Bordspel? bordspel = repositoryBordspellen.GetBordspelById(id);
            return View(bordspel);
        }

        //POST: Bordspel/Edit/{?id}
        [Authorize(Policy = "Gebruiker")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Bordspel bordspelModel, IFormFile imageFile)
        {
            if (imageFile != null)
            {
                imageConverter(bordspelModel, imageFile);
                Task.Delay(1000);
            }
            var id = _userManager.GetUserId(User);
            bordspelModel.GebruikerId = id;
            ModelState.Remove("imageFile");
            ModelState.Remove("GebruikerId");
            if (ModelState.IsValid)
            {
                repositoryBordspellen.UpdateBordspel(bordspelModel);
                repositoryBordspellen.save();
                return RedirectToAction("Index");
            }
            return View(bordspelModel);
        }



        //DELETE: Bordspel/Delete/{?id}
        [Authorize(Policy = "Gebruiker")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult<Bordspel> DeleteConfirmed(int id)
        {
            repositoryBordspellen.DeleteBordspel(id);
            repositoryBordspellen.save();
            return RedirectToAction(nameof(Index));

        }

        protected override void Dispose(bool disposing)
        {
            repositoryBordspellen.Dispose();
            base.Dispose(disposing);
        }
    }
}

AvondspelPortal/Controllers/BordspellenAvondController.cs
using Avondspel.Domain;
using Avondspel.Services;
using Avondspel.Services.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace Avondspel.Portal.Controllers
{
    public class BordspellenAvondController : Controller
    {
        private readonly IRepositoryBordspellenAvond _repositoryBordspellenAvond;
        private readonly IRepositoryBordspelLijst _repositoryBordspelLijst;
        private readonly IRepositoryBordspellen _repositoryBordspellen;
        private readonly IRepositoryGebruiker _repositoryGebruiker;
        private readonly IRepositoryEten _repositoryEten;

        private readonly IBordspellenAvondDomainService _bordspellenAvondDomainService;

        private readonly UserManager<IdentityUser> _userManager;

        public BordspellenAvondController(IBordspellenAvondDomainService bordspellenAvondDomainService, IRepositoryEten repositoryEten, IRepositoryBordspellenAvond repositoryBordspellenAvond, UserManager<IdentityUser> userManager, IRepositoryBordspelLijst repositoryBordspelLijst, IRepositoryBordspellen repositoryBordspellen, IRepositoryGebruiker repositoryGebruiker)
        {
            _repositoryBordspelLijst = repositoryBordspelLijst;
            _repositoryBordspellenAvond = repositoryBordspellenAvond;
            _repositoryBordspellen = repositoryBordspellen;
            _userManager = userManager;
            _repositoryGebruiker = repositoryGebruiker;
            _repositoryEten = repositoryEten;
            _bordspellenAvondDomainService = bordspellenAvondDomainService;
        }

        //GET : BordspellenAvond
        [Authorize(Policy = "Gebruiker")]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                try
                {
                    var emailUser = _bordspellenAvondDomainService.getGebruikerByEmail(user.Email);
                    var bordspellenAvond = _bordspellenAvondDomainService.GetBordspellenAvonden(emailUser);
                    ViewBag.Gebruiker = emailUser;
                    return View(bordspellenAvond);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            }
            return View();
        }

        //GET : BordspellenAvond/Gebruiker
        [Authorize(Policy = "Gebruiker")]
        public IActionResult Gebruiker()
        {
            try
            {
                var id = _userManager.GetUserId(User);
                var bordspellenAvond = from BordspellenAvond in _bordspellenAvondDomainService.getBordspellenAvondMetUser(id) select BordspellenAvond;
                return View(bordspellenAvond);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return RedirectToAction("Index");
        }

        //GET : BordspellenAvond/GebruikerInAvonden
        [Authorize(Policy = "Gebruiker")]
        public async Task<IActionResult> GebruikerInAvonden()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                Gebruiker? gebruiker = _bordspellenAvondDomainService.getGebruikerByEmail(user.Email);
                if (gebruiker == null)
                {
                    throw new Exception("gebruiker is null");
                }
                else
                {
                    var bevattend = _bordspellenAvondDomainService.GetBordspellenAvondMetGebruikerId(gebruiker.Id);
                    var lijstAvondenMetGebruiker = new List<BordspellenAvond>();

                    if (bevattend != null)
                    {
                        if (bevattend.Any())
                        {
                            foreach (var gebruikerIn in bevattend)
                            {
                                if (gebruikerIn != null)
                                {
                                    var avondMetGebruiker = _bordspellenAvondDomainService.getBordspellenAvondMetId(gebruikerIn.Id);
                                    if (avondMetGebruiker != null)
                                    {
                                        lijstAvondenMetGebruiker.Add(gebruikerIn);
                                    }

                                }
                            }
                            ViewBag.lijstAvondenMetGebruiker = lijstAvondenMetGebruiker;
                        }
                        else
                        {
                            ViewBag.lijstAvondenMetGebruiker = null;
                        }
                    }
                    else
                    {
                        ViewBag.lijstAvondenMetGebruiker = null;
                    }

                    return View();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return View();
        }

        //GET : BordspellenAvond/Details/{?id}
        [Authorize(Policy = "Gebruiker")]
        public async Task<ViewResult> Details(int id)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var gebruiker = _bordspellenAvondDomainService.getGebruikerByEmail(user.Email);
                BordspellenAvond? bordspellenAvond = _bordspellenAvondDomainService.getBordspellenAvondMetId(id);
                var bordspelData = _bordspellenAvondDomainService.GetBordspellenLijstByAvond(id);
                
                bool isEmpty = true;
                bool isOwner = false;
                var lijstBordspel = new List<Bordspel>();

                if (bordspellenAvond != null)
                {
                    if (bordspellenAvond.Gebruikers.Any())
                    {
                        isEmpty = false;
                    }
                    if (user.Id.Equals(bordspellenAvond.GebruikerId))
                    {
                        isOwner = true;
                    }
                }
                if (bordspelData != null)
                {
                    foreach (var bordspel in bordspelData)
                    {
                        var bordspelUitLijst = _repositoryBordspellen.GetBordspelById(bordspel.BordspelId);
                        if (bordspelUitLijst != null)
                        {
                            lijstBordspel.Add(bordspelUitLijst);
                        }
                    }
                }
                if (gebruiker != null)
                {
                    ViewBag.Gebruiker = gebruiker;
                } else
                {
                    Console.WriteLine("Geen gebruiker gevonden");
                }

                ViewBag.isEmpty = isEmpty;
                ViewBag.isOwner = isOwner;
                ViewBag.BordspelLijst = lijstBordspel;

                return View(bordspellenAvond);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return View();
        }

        //GET : BordspellenAvond/Create
        [Authorize(Policy = "Gebruiker")]
        public IActionResult Create()
        {
            try
            {
                var bordspellenData = _bordspellenAvondDomainService.GetBordspellen();
                var etenData = _bordspellenAvondDomainService.GetEten();
                var lijst = new List<SelectListItem>();
                var lijstEten = new List<SelectListItem>();
                foreach (var bordspel in bordspellenData)
                {
                    lijst.Add(new SelectListItem { Text = bordspel.Naam, Value = bordspel.Id.ToString() });
                }
                foreach (var eten in etenData)
                {
                    lijstEten.Add(new SelectListItem { Text = eten.Name, Value = eten.Id.ToString() });
                }
                if (lijstEten.Count > 0)
                {
                    ViewBag.eten = lijstEten;
                }

                ViewBag.bordspellen = lijst;
                return View();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return View();
        }

        //POST : BordspellenAvond/Create
        [Authorize(Policy = "Gebruiker")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BordspellenAvond bordspellenAvond, List<string> bordspellen, List<string> etenLijst)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                bordspellenAvond.GebruikerId = user.Id;
                ModelState.Remove("GebruikerId");
                var gebruiker = _bordspellenAvondDomainService.getGebruikerByEmail(user.Email);

                if (!etenLijst.Any())
                {
                    bordspellenAvond.PotLuck = true;
                }
                else
                {
                    foreach (var x in etenLijst)
                    {
                        var eten = _bordspellenAvondDomainService.GetEtenById(int.Parse(x));
                        if (eten != null)
                        {
                            bordspellenAvond.EtenLijst.Add(eten);
                        }
                    }
                }

                if (ModelState.IsValid)
                {
                    foreach (var item in bordspellen)
                    {
                        if (item != null)
                        {
                            var bordspel = _bordspellenAvondDomainService.GetBordspelById(int.Parse(item));

AvondspelPortal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="card w-100">
    <div class="card-body">
        <div class="row">
            <div class="col-auto me-auto">
                <a asp-controller="Bordspel" asp-action="Index" class="btn btn-primary">Bordspellen</a>
            </div>
            <div class="col-auto">
                <a asp-controller="BordspellenAvond" asp-action="Index" class="btn btn-primary">Avonden</a>
            </div>
        </div>
        <div class="row ">
            <div class="text-center fs-1 mt-1 mb-5">
                Welkom @ViewBag.gebruiker
            </div>
        </div>
        @if (!User.Identity.IsAuthenticated)
        {
            <div class="row">
                <div class="col-auto me-auto">
                    <a asp-controller="Home" asp-action="Login" class="btn btn-primary">Login</a>
                </div>
                <div class="col-auto">
                    <a asp-controller="Home" asp-action="Registreren" class="btn btn-primary">Meld je aan</a>
                </div>
            </div>
        }

    </div>
</div>

AvondspelPortal/Views/Home/LeeftijdError.cshtml
<div>
    Je bent nog te jong om een bordspellenavond aan te maken en organisator te worden
</div>
<div>
    Je bent nog te jong om mee te doen aan een avond met als leeftijdsgrens 18+
</div>

AvondspelPortal/Views/Home/Login.cshtml
@model Avondspel.Portal.Models.LoginViewModel

<div class="card w-100">
    <div class="card-header">
        <h1>Login</h1>
    </div>
    <div class="card-body">
        <form asp-action="Login" asp-controller="Home" method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-group">
                <label class="form-label" asp-for="Email"></label>
                <div><span asp-validation-for="Email" class="text-danger"></span></div>
                <input class="form-control" asp-for="Email" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" asp-for="Password"></label>
                <div><span asp-validation-for="Password" class="text-danger"></span></div>
                <input class="form-control" asp-for="Password" />
            </div>
            <div class="row">
                <div class="col align-self-start">
                    <button class="btn btn-primary" type="submit">Login</button>
                </div>
                <div class="col-auto">
                    <a asp-action="Registreren" asp-controller="Home" class="btn btn-primary ">Maak een account aan</a>
                </div>
            </div>
        </form>
    </div>
</div>

AvondspelPortal/Views/Home/Profiel.cshtml
@model Avondspel.Domain.Gebruiker

@{
    ViewData["Title"] = "Profiel";
}
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-3">
            <div class="card mb-3">
                <div class="card-header">Je profiel</div>
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(model => model.Name)</h5>
                    <p class="card-text">Mail: @Html.DisplayFor(model => model.Email)</p>
                    <p class="card-text">Geslacht: @Html.DisplayFor(model => model.Gender)</p>
                    <p class="card-text">Geboortedatum: @Html.DisplayFor(model => model.Birthday)</p>
                    <p class="card-text">Adres: @Html.DisplayFor(model => model.Street) @Html.DisplayFor(model => model.HouseNumber), @Html.DisplayFor(model => model.City)</p>
                    <p class="mb-0">Dieet:</p>
                    @if (Model.Lactose == true)
                    {
                        <p class="mb-0">Lactose allergie</p>
                    }
                    @if (Model.Alcohol == true)
                    {
                        <p class="mb-0">Drinkt geen alcohol</p>
                    }
                    @if (Model.Notenallergie == true)
                    {
                        <p class="mb-0">Noten allergie</p>
                    }
                    @if (Model.Vega == true)
                    {
                        <p class="mb-0">Vegatarisch</p>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="row align-items-start">
        <div class="col-md-6 mb-4">
            <h4 class="font-weight-bold">Jouw avonden die gepland staan</h4>
            @if (ViewBag.lijstAvonden != null)
            {
                @foreach (var item in ViewBag.lijstAvonden)
                {
                    <partial name="_Avonden" model="item" />
                }
            }
            else
            {
                <partial name="_ErrorLijstLeeg" />
            }

            <a asp-action="Gebruiker" asp-controller="BordspellenAvond">jouw lijst</a>
        </div>
        <div class="col-md-6">
            <h4 class="font-weight-bold">Avonden waar jij aan meedoet</h4>
            @if (ViewBag.lijstAvondenMetGebruiker != null)
            {
                @foreach (var item in ViewBag.lijstAvondenMetGebruiker)
                {
                    <partial name="_Avonden" model="item" />
                }
            }
            else
            {
                <partial name="_ErrorLijstLeeg" />
            }

            <a asp-action="GebruikerInAvonden" asp-controller="BordspellenAvond">lijsten waar je inzit</a>
        </div>
    </div>
</div>

AvondspelPortal/Views/Home/Registreren.cshtml
@model Avondspel.Portal.Models.LoginViewModel
@using Avondspel.Domain.Enum

<div class="card w-100">
    <div class="card-header">
        <h1>Registreren</h1>
    </div>
    <div class="card-body">
        <form asp-action="Registreren" asp-controller="Home" method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-group">
                <label class="form-label" asp-for="Name">Naam</label>
                <div><span asp-validation-for="Name" class="text-danger"></span></div>
                <input class="form-control" asp-for="Name" />
            </div>
            <div class="form-group">
                <label class="form-label" asp-for="Email"></label>
                <div><span asp-validation-for="Email" class="text-danger"></span></div>
                <input class="form-control" asp-for="Email" />
            </div>
            <div class="form-group">
                <label class="form-label" asp-for="Gender"></label>
                <div class="row">
                    <div class="col">
                        <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Geslacht>()">
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="form-label" asp-for="Birthday">Geboortedatum</label>
                <div><span asp-validation-for="Birthday" class="text-danger"></span></div>
                <input class="form-control" asp-for="Birthday" type="date" />
            </div>
            <div class="form-group">
                <label class="form-label" asp-for="Street">Straat</label>
                <div><span asp-validation-for="Street" class="text-danger"></span></div>
                <input class="form-control" asp-for="Street" />
            </div>
            <div class="form-group">
                <label class="form-label" asp-for="City">Stad</label>
                <div><span asp-validation-for="City" class="text-danger"></span></div>
                <input class="form-control" asp-for="City" />
            </div>
            <div class="form-group">
                <label class="form-label" asp-for="HouseNumber">Huisnummer</label>
                <div><span asp-validation-for="HouseNumber" class="text-danger"></span></div>
                <input class="form-control" asp-for="HouseNumber" />
            </div>
            <div class="form-group  mb-3">
                <label class="form-label" asp-for="Password"></label>
                <div><span asp-validation-for="Password" class="text-danger"></span></div>
                <input class="form-control" asp-for="Password" />
            </div>

            <div class="list-group mb-3">
                <label class="list-group-item" asp-for="Lactose">
                    <input class="form-check-input me-1" type="checkbox" asp-for="Lactose">
                    Lactose
                </label>
                <div><span asp-validation-for="Lactose" class="text-danger"></span></div>
            </div>

            <div class="list-group mb-3">
                <label class="list-group-item" asp-for="Notenallergie">
                    <input class="form-check-input me-1" type="checkbox" asp-for="Notenallergie">
                    Notenallergie
                </label>
                <div><span asp-validation-for="Notenallergie" class="text-danger"></span></div>
            </div>

            <div class="list-group mb-3">
                <label class="list-group-item" asp-for="Vega">
                    <input class="form-check-input me-1" type="checkbox" asp-for="Vega">
                    veganist / vegetariër
                </label>
                <div><span asp-validation-for="Vega" class="text-danger"></span></div>
            </div>

            <div class="list-group mb-3">
                <label class="list-group-item" asp-for="Alcohol">
                    <input class="form-check-input me-1" type="checkbox" asp-for="Alcohol">
                    Geen Alcohol
                </label>
                <div><span asp-validation-for="Alcohol" class="text-danger"></span></div>
            </div>
            <div class="row">
                <div class="col align-self-start">
                    <button class="btn btn-primary" type="submit">Registreren</button>
                </div>
                <div class="col-auto">
                    <a asp-action="Login" asp-controller="Home" class="btn btn-primary ">Login</a>
                </div>
            </div>
        </form>
    </div>
</div>